server:
  port: 9000
  servlet:
    session:
      cookie:
        name: AUTHSERVERSESSIONID
security:
  jwt:
    key-store: classpath:keystore.jks
    key-store-password: letmein
    key-pair-alias: mytestkey
    key-pair-password: changeme
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  datasource:
    #url: jdbc:postgresql://localhost:5432/authorization-server-db
    url: jdbc:h2:mem:testDB;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS authorization_server_schema;
    username: postgres
    password: root
    #schema: classpath:db/schema.sql
    #data: classpath:db/data.sql
    #driver-class-name: org.postgresql.Driver
    driver-class-name: org.h2.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 20
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            #noncontextual lob creation switch-on
            #https://github.com/spring-projects/spring-boot/issues/12007#issuecomment-369388646
            non_contextual_creation: true
        format_sql: true
        #ddl-auto: validate
        ddl-auto: create-drop
        #dialect: org.hibernate.dialect.PostgreSQLDialect
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
logging:
  level:
    org.springframework.security: DEBUG